#!/bin/bash
set -euo pipefail

#############################################
# ASL3 Node Connector Script
# By Goose - N8GMZ - 2025-2026
# https://github.com/GooseThings/ASL3-node-connector/
#
# Connects your node to a target node (typically for a scheduled net),
# monitors for activity, and disconnects after the net goes idle.
# Designed to be started from cron shortly before net time.
#############################################

# --- DEFAULT SETTINGS ---------------------------------------------------
# Do not edit this file to configure the script. Put your settings in
# /etc/asl3-node-connector.conf instead (the setup script writes it for
# you) — that way they survive script upgrades. Any variable set in the
# conf file overrides the default below.
NODE=""                                          # your local node number (REQUIRED)
TARGET=""                                        # node to connect to (REQUIRED)
IDLE_LIMIT=180                                   # seconds of idle time before disconnect
NET_SETTLE_TIME=300                              # seconds to wait after connecting before idle monitoring starts
IDLE_POLL_INTERVAL=30                            # seconds between idle checks
PERMANENT_LINK=false                             # true: use *813/*811 (permanent link; needs rpt.conf functions 811/813)
                                                 # false: use *3/*1 (normal link; needs rpt.conf functions 1/3)
AUDIO_PATH="/var/lib/asterisk/sounds/custom"     # directory holding the announcement audio (asterisk must own the files)
EARLY_ANNOUNCE=""                                # early-warning announcement filename, no extension ("" disables)
EARLY_TIME=600                                   # seconds between the early announcement and the connect phase
CONNECT_ANNOUNCE=""                              # played right before connecting ("" disables)
CONNECT_ANNOUNCE_TIME=20                         # dwell after the connect announcement — must be at least as long as
                                                 # the audio, or it will still be playing when the link comes up and
                                                 # be heard on the far node
DISCONNECT_ANNOUNCE=""                           # played right after disconnecting ("" disables)
LOGFILE="/var/log/ASL3-node-connector.log"       # action log file
LOG_MAX_BYTES=1048576                            # rotate the log to .old when it exceeds this (1 MB)
ASTERISK_BIN="/usr/sbin/asterisk"                # full path to asterisk binary (PATH is minimal under cron)
CONNECT_TRIES=3                                  # how many times to send the connect/disconnect command
VERIFY_WAIT=10                                   # seconds to wait for the link state to change after each try
# ------------------------------------------------------------------------

CONFIG_FILE="/etc/asl3-node-connector.conf"
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
fi

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo "DRY RUN MODE ENABLED — No commands will be executed - Verbose output will commence"
fi

log() {
    # Never let logging kill the script (set -e): a read-only or missing log
    # target degrades to console-only output instead of a silent cron death.
    local line
    line="$(date '+%Y-%m-%d %H:%M:%S') $*"
    echo "$line"
    echo "$line" >> "$LOGFILE" 2>/dev/null || true
}

rotate_log() {
    local size
    size=$(stat -c %s "$LOGFILE" 2>/dev/null) || return 0
    if (( size > LOG_MAX_BYTES )); then
        mv -f "$LOGFILE" "$LOGFILE.old" 2>/dev/null || true
    fi
}

run_asterisk_cmd() {
    if $DRY_RUN; then
        log "[DRY RUN] Would run: asterisk -rx \"$*\""
    else
        "$ASTERISK_BIN" -rx "$@"
    fi
}

# play <name> — plays $AUDIO_PATH/<name> on the local node only.
# 'rpt localplay' keys only the local transmitter; 'rpt playback' (used by
# older versions of this script) also transmits over every connected link,
# which is not what you want for a local "net starting soon" announcement.
play() {
    if $DRY_RUN; then
        log "[DRY RUN] Would play: $AUDIO_PATH/$1"
    else
        "$ASTERISK_BIN" -rx "rpt localplay $NODE $AUDIO_PATH/$1"
    fi
}

# announce <name> <dwell-seconds> — play an announcement (if configured) and
# wait for it to finish. A missing file is a warning, not a fatal error: the
# net connection matters more than the courtesy audio.
announce() {
    local name="$1" dwell="$2"
    [[ -n "$name" ]] || return 0
    if [[ ! -f "$AUDIO_PATH/$name.wav" && ! -f "$AUDIO_PATH/$name.ulaw" ]]; then
        log "WARN: announcement audio not found: $AUDIO_PATH/$name.{wav,ulaw} — skipping"
        return 0
    fi
    play "$name"
    sleep "$dwell"
}

# get_keyed_status
#
# Sets globals RXKEYED and TXKEYED to "0" (idle), "1" (keyed), or "" (unknown).
# Returns 0 on a successful, parseable read; returns non-zero if the asterisk
# query failed or the keyed values could not be parsed. Callers MUST check the
# return value and treat a failure as "unknown" — never as "active" — otherwise
# transient CLI failures will continually reset the idle timer and the script
# will never disconnect.
get_keyed_status() {
    local output rc
    rc=0

    # Capture asterisk output without letting `set -e` abort the script if it fails.
    output=$("$ASTERISK_BIN" -rx "rpt show variables $NODE" 2>/dev/null) || rc=$?

    if (( rc != 0 )) || [[ -z "$output" ]]; then
        RXKEYED=""
        TXKEYED=""
        log "WARN: failed to read asterisk variables (rc=$rc, empty=$([[ -z "$output" ]] && echo yes || echo no))"
        return 1
    fi

    RXKEYED=$(echo "$output" | awk -F= '/RPT_RXKEYED/ {gsub(/^[ \t]+|[ \t\r\n]+$/, "", $2); print $2; exit}')
    TXKEYED=$(echo "$output" | awk -F= '/RPT_TXKEYED/ {gsub(/^[ \t]+|[ \t\r\n]+$/, "", $2); print $2; exit}')

    RXKEYED=$(echo "$RXKEYED" | tr -d '\r\n[:space:]')
    TXKEYED=$(echo "$TXKEYED" | tr -d '\r\n[:space:]')

    # If we got no value, treat as unknown (NOT active). Empty / non-0 / non-1
    # all collapse to "" so the caller can distinguish unknown from idle.
    [[ "$RXKEYED" == "0" || "$RXKEYED" == "1" ]] || RXKEYED=""
    [[ "$TXKEYED" == "0" || "$TXKEYED" == "1" ]] || TXKEYED=""

    if [[ -z "$RXKEYED" || -z "$TXKEYED" ]]; then
        return 1
    fi
    return 0
}

# link_connected — is TARGET currently linked to NODE?
# Returns 0 (yes), 1 (no), 2 (could not determine).
link_connected() {
    local output
    output=$("$ASTERISK_BIN" -rx "rpt lstats $NODE" 2>/dev/null) || return 2
    [[ -n "$output" ]] || return 2
    if echo "$output" | awk 'NR > 2 {print $1}' | grep -qx "$TARGET"; then
        return 0
    fi
    return 1
}

# set_link <connect|disconnect> — send the link command and VERIFY the state
# actually changed. `asterisk -rx "rpt fun ..."` exits 0 even when the
# function is commented out in rpt.conf (the most common install problem),
# so trusting the exit code silently does nothing — read the real link state
# back instead. Retries the command up to CONNECT_TRIES times.
set_link() {
    local action="$1" fun want try waited
    if [[ "$action" == "connect" ]]; then
        fun="*3"; $PERMANENT_LINK && fun="*813"
        want=0
    else
        fun="*1"; $PERMANENT_LINK && fun="*811"
        want=1
    fi

    for (( try = 1; try <= CONNECT_TRIES; try++ )); do
        run_asterisk_cmd "rpt fun $NODE ${fun}${TARGET}"
        if $DRY_RUN; then
            return 0
        fi

        waited=0
        while (( waited < VERIFY_WAIT )); do
            sleep 2
            waited=$(( waited + 2 ))
            local state=0
            link_connected || state=$?
            if (( state == want )); then
                log "Verified: $action of node $TARGET took effect."
                return 0
            fi
        done
        log "WARN: $action of node $TARGET not confirmed after attempt $try/$CONNECT_TRIES — retrying"
    done

    log "ERROR: could not $action node $TARGET after $CONNECT_TRIES attempts."
    log "ERROR: check that the required rpt.conf [functions] entries are uncommented"
    log "ERROR: ($($PERMANENT_LINK && echo '811/813 for permanent links' || echo '1/3 for normal links')) and reload asterisk."
    return 1
}

# --- PRE-FLIGHT CHECKS ---------------------------------------------------
rotate_log

errors=0
if [[ ! "$NODE" =~ ^[0-9]+$ ]]; then
    log "ERROR: NODE is not set (or not a number). Configure it in $CONFIG_FILE."
    errors=1
fi
if [[ ! "$TARGET" =~ ^[0-9]+$ ]]; then
    log "ERROR: TARGET is not set (or not a number). Configure it in $CONFIG_FILE."
    errors=1
fi
if [[ ! -x "$ASTERISK_BIN" ]]; then
    log "ERROR: asterisk binary not found at $ASTERISK_BIN."
    errors=1
fi
if (( errors )); then
    log "Pre-flight checks failed — exiting."
    exit 1
fi

# Single-instance lock (per local node). Without this, a hung run from a
# previous net plus this week's cron entry means two scripts fighting over
# the same link — one connecting while the other disconnects.
LOCKFILE="/var/lock/asl3-node-connector-$NODE.lock"
exec 9>"$LOCKFILE"
if ! flock -n 9; then
    log "Another instance is already running for node $NODE (lock: $LOCKFILE) — exiting."
    exit 1
fi

# --- STEP 1: Early-warning announcement (optional) ------------------------
if [[ -n "$EARLY_ANNOUNCE" ]]; then
    log "Waiting for repeater to be idle before early announcement..."
    start_wait=$(date +%s)
    while :; do
        if ! get_keyed_status; then
            log "Retrying due to parse error..."
        elif [[ "$RXKEYED" == "0" && "$TXKEYED" == "0" ]]; then
            log "Repeater idle. Playing early announcement."
            announce "$EARLY_ANNOUNCE" 0
            break
        else
            log "Repeater busy. Rechecking in 20s..."
        fi

        if (( $(date +%s) - start_wait > 120 )); then  # Force announcement after 2 minutes
            log "Timeout waiting for idle before early announcement — forcing continue."
            announce "$EARLY_ANNOUNCE" 0
            break
        fi
        sleep 20
    done
    log "Early announcement done. Connecting in $EARLY_TIME seconds..."
    sleep "$EARLY_TIME"
fi

# --- STEP 2: Wait for repeater to be idle, then connect -------------------
log "Waiting for repeater to be idle before connecting..."
start_wait=$(date +%s)
while :; do
    if ! get_keyed_status; then
        log "Retrying due to parse error..."
    elif [[ "$RXKEYED" == "0" && "$TXKEYED" == "0" ]]; then
        announce "$CONNECT_ANNOUNCE" "$CONNECT_ANNOUNCE_TIME"
        log "Connecting to node $TARGET..."
        set_link connect || exit 1
        break
    else
        log "Repeater busy. Rechecking in 20s..."
    fi

    if (( $(date +%s) - start_wait > 120 )); then  # Force connection after 2 minutes
        log "Timeout waiting for idle before connect — forcing connection"
        announce "$CONNECT_ANNOUNCE" "$CONNECT_ANNOUNCE_TIME"
        log "Forced connecting to node $TARGET..."
        set_link connect || exit 1
        break
    fi
    sleep 20
done

log "Successfully connected to node. Pausing $NET_SETTLE_TIME seconds before monitoring for idle..."
sleep "$NET_SETTLE_TIME"  # Let the net settle in case it starts late.

# --- STEP 3: Monitor for idle time -----------------------------------------
log "Monitoring for idle time (limit: $IDLE_LIMIT seconds)..."
LAST_ACTIVITY=$(date +%s)
CONSECUTIVE_PARSE_FAILURES=0
MAX_PARSE_FAILURES=20  # ~10 minutes at the default 30s poll — bail out rather than hang forever

while :; do
    CURRENT_TIME=$(date +%s)

    if ! get_keyed_status; then
        # Could not determine state. Do NOT reset the timer (that was the old bug),
        # and do NOT count this poll as activity. Just skip and try again.
        CONSECUTIVE_PARSE_FAILURES=$(( CONSECUTIVE_PARSE_FAILURES + 1 ))
        log "WARN: keyed status unknown — skipping this poll (failure ${CONSECUTIVE_PARSE_FAILURES}/${MAX_PARSE_FAILURES})"

        if (( CONSECUTIVE_PARSE_FAILURES >= MAX_PARSE_FAILURES )); then
            log "ERROR: too many consecutive parse failures. Forcing disconnect from node $TARGET as a safety measure..."
            set_link disconnect || true
            announce "$DISCONNECT_ANNOUNCE" 0
            log "Disconnected from node $TARGET (forced due to repeated parse failures)"
            exit 1
        fi
    else
        CONSECUTIVE_PARSE_FAILURES=0

        if [[ "$RXKEYED" == "1" || "$TXKEYED" == "1" ]]; then
            LAST_ACTIVITY=$CURRENT_TIME
            log "Activity detected. Timer reset."
        else
            IDLE_TIME=$((CURRENT_TIME - LAST_ACTIVITY))
            log "Idle time: $IDLE_TIME seconds."
        fi

        if (( CURRENT_TIME - LAST_ACTIVITY >= IDLE_LIMIT )); then
            log "Idle time exceeded. Disconnecting from node $TARGET..."
            set_link disconnect || exit 1
            announce "$DISCONNECT_ANNOUNCE" 0
            log "Disconnected from node $TARGET"
            exit 0
        fi
    fi

    sleep "$IDLE_POLL_INTERVAL"
done
